### PR TITLE
Changes for 2 player control

### PR DESCRIPTION
**Pull request by fragmental**
This should add 2 player support for both controllers and incomplete keyboard controls
for two players, both paddles will need to be selected for this to work

on keyboard
left player is w and s.  right is up and down

on joystick
left and right buttons should control your side of the flippers
up and down on either left analog or direction pad should work(may differ depending on player. need to fix that)

The change to main menu scene can be quickly redone.  Toss them if need be.  They're important but super easy.

Unfortunately a lot of this I wasn't able to test because unity stopped responding to my controllers for no reason.

### CODE REVIEW

**Comment by Cheeseness** [comment]
I can't get the powers shortcuts working, and flippers seem to be missing from Table02 (could be a case issue somewhere, I guess?)

I'm uncomfortable merging this as-is right before doing an end-of-day build. Hopefully @lightsoda will get a chance to look over it before morning.

**Comment by fragmental** [comment]
I didn't know ow how to tell if powers were working so couldn't test.  And
flippers missing is a variant issue that's fixed by copying the flipper
prefab to the other variant folder, but no one has bothered to do it.

**Comment by fragmental** [comment]
:(

**Comment by Cheeseness** [comment]
Powers become available every 30 seconds. If they're working, you'll see either a large black square, a small grey cube or a blue transparent circle when activating them (currently randomly picked between the three) - the cube is the least obvious one, but should still be pretty easy to spot - it's meant to spawn at the opponent's paddle location.

Good to know what's up with the missing flipper ^_^

**Comment by fragmental** [comment]
Oh.  I didn't check to see how this could affect network play.

**Comment by Cheeseness** [comment]
It seemed OK from my testing, but I was mostly focusing on making sure that single player functionality was there first, so I don't feel like I was thorough on the networking front.

**Comment by ghost** [comment]
I'll have a look at this after rebasing kgunns branch from yesterday.

**Comment by fragmental** [comment]
I can rebase this

**Comment by fragmental** [comment]
Looks like someone named paddleIndex to playerIndex in Menu.SetupTable?

**Comment by fragmental** [comment]
I was kind of hoping this would get merged, because I knew if it didn't there would be merge conflicts later.  

I rebased, and threw out my copy of basemenu and then redid my changes in basemenu but then sourctree wouldn't push to the repo, because of the changes that were in the repo(the previous paddleindex stuff I had previously discarded) and now I accidentally overwrote with the wrong copy and don't know how to go back so I'm giving up.  

All I've done is waste my time.

**Comment by ghost** [comment]
I'm sorry @fragmental 

I'll give a go at rebasing the branch. There are no recent changes to it so I assume it's still in its PR state.

**Comment by Cheeseness** [comment]
> All I've done is waste my time.

Nothing's been lost. We'll get your changes in :)

**Comment by Cheeseness** [comment]
Superseded by #91

**Pull request closed without merging**
