### PR TITLE
Game menu ugui

### PR DESCRIPTION
**Pull request by jctwizard**
Adds new ui

### CODE REVIEW

**Comment by Cheeseness** [comment]
OK, some notes. I'd like to get these things sorted, but I'd also like to try to merge osse's PR, so I'm going to switch to that for the moment and we can work out how to tackle this when you get back to your desk.

* "Play"  and "Online" buttons (change to "offline" or "online")
* Text size on buttons/labels should be consistent (probably not a big deal right now, but worth mentioning)
* UI background lingers during gameplay
* IP address and port text areas are out of alignment
network_ui

Longer term, we probably also want to address
* It would be good to have per-player paddle selection
* Unify single/two player and have AI selected as part of paddle selection?

**Comment by fragmental** [comment]
Ping me if you need me.  Here or forums or email(or something better?)  Irc seems like a no go for me for a minute.

**Comment by jctwizard** [comment]
Most everything is working that was mentioned above. I added an issue for the paddle selection.

**Comment by Cheeseness** [comment]
This seems to test well. Still needs some refinement longer term, but is a much more scalable UI that we can pretty up later! Woohoo!

**Review by fragmental — COMMENTED** [review]
\o/

**Pull request merged**
