### PR TITLE
Implemented table_kednar and my variants - seems to work!

### PR DESCRIPTION
**Pull request by kednar**

### CODE REVIEW

**Review by Cheeseness — CHANGES_REQUESTED** [review]
This is looking great! Good job on pulling it all together!

It's got some things that I think should be addressed before merging though:

* Shared materials should go in the Assets/entities/shared/Materials folder
* The ceiling needs to be lowered so that the ball can't bounce over paddles (it might need to be curved to match the terrain!)
* Your table doesn't seem to use the variant system properly (selecting other variants doesn't use their bumpers, etc.)
* Bumpers need to be given the bumper tag so that they'll make bumper sounds
* Walls need to be given the wall tag so that they'll make wall sounds
* The camera doesn't seem to automatically zoom out to show the entire table (possibly a camera script bug!)

Other than that, it looks good!

**Comment by kednar** [comment]
Heh! I knew I was missing something :D
Sadly I am out until later, could you please reach KGuNN so he fixes it?
Thank you!

**Comment by kednar** [comment]
Note: the ceiling mesh is already curved as the ground.

**Comment by Cheeseness** [comment]
> Note: the ceiling mesh is already curved as the ground.

Ah, OK! I think it needs to be lowered then. The new paddle collider is very tall compared to the old one and it still bounces overhead pretty often.

**Comment by fragmental** [comment]
I think you can also make unity cubes, position them, and turn off their mesh render.  Not ideal but might be useful in some situations.

**Comment by Cheeseness** [comment]
I think we want to address a couple of things (lightpad behaviour, separating wall geometry and maybe trying to deal with the one-sidedness of the spinner, but other than that, it's looking good enough for now!

Merged! \o/

**Comment by fragmental** [comment]
Gj @kednar \o/

**Comment by fragmental** [comment]
Importing tables can sometimes be a pita.  I know this from experience.  I
probably should have made some concrete import instructions when I first
successfully imported table2

**Pull request merged**
