### PR TITLE
Music Testing Debug.Log by Pressing "T"

### PR DESCRIPTION
**Pull request by fragmental**
Added a function that prints the results of musicSource.isPlaying to the debug.log for testing #151

### CODE REVIEW

**Comment by ghost** [comment]
Can't you just test this locally? Why a PR.

**Comment by fragmental** [comment]
I can and will test it locally when I'm awake later.  The pr is in case
anyone else wants to test.  Since this bug doesn't happen often or
regularly.

**Comment by fragmental** [comment]
And it's for @Cheeseness.  He wanted to know if isPlaying was running when
the bug happened so I added some code to do that.

**Comment by fragmental** [comment]
And I'm going to sleep

**Comment by Cheeseness** [comment]
To avoid confusion, let's keep PRs for code that we want merged into the main codebase. It's better to link to a branch if your own fork with this kind of stuff.

**Pull request closed without merging**
