### PR TITLE
KGunn table1_02

### PR DESCRIPTION
**Pull request by fragmental**
I dropped everything into a singular folder, added colliders, and then imported it into the scene and attached the necessary scripts.

### CODE REVIEW

**Comment by ghost** [comment]
The components of the table should be in Assets > entities > variant-kgunn.

With the same name as they currently have

- ball
- bumper
- flipper

etc

This also means that the bumper model can't contain _all_ bumpers, just one, we place, rotate and duplicate in unity. Same goes for the other model files.

The table itself doesn't matter, the previous ones are in shared. Though I guess this one should replace the existing one.

**Comment by fragmental** [comment]
There was a miscommunication between @KGuNN45 and I about how files needed to be exported.

What I was trying to say to him was to export the playfield as one fbx, and then export the entities like ball, bumper, flipper, etc as a single object on its own and then export one fbx with everything in it so that it can be used just to get the placement right, of the prefabs.  I must have miscommunicated.

But I don't know if ball,bumper, and flipper have changed either.   Also, afik, maya has some tools that are really useful for accurately placing objects that unity doesn't have, like mirroring around a coordinate in space(But  I could be wrong).  So where things need to be meticulously placed, like the tunnels and ramps or the "slingshots" there might be an advantage to importing them as a group from the modeling software.

**Comment by Cheeseness** [comment]
So far as I can tell, stuff like Assets/entities/kgunn_table1/popBumper_TestTable01_kgunn.fbx (and associated mats/prefabs) for which we're aiming to have as assetbundle variants is redundant and doesn't belong in the main repo (totally fine for that to be used as a guide for placing individual elements, but I think if anybody needs that, getting it from the assets repo should be enough?).

@fragmental was also saying in IRC that none of the stuff in this PR is used by the game? I thought we'd decided that all this would replace the existing kgunn variant and table, so this confuses me.

**Comment by fragmental** [comment]
I never said that none of this stuff is used.  I said that none of Kgunn's
bumper models are used.  It's basically a sphere.  Might be just a
placeholder.

**Comment by fragmental** [comment]
And I'm not sure that variants and the asset bundler are doing anything?

**Comment by ghost** [comment]
> And I'm not sure that variants and the asset bundler are doing anything?

Kgunns bumpers are loaded with that variant, but as you said they are just spheres, and could just as well be placeholders.

**Comment by fragmental** [comment]
During testing, the bumpers appeared to be the same regardless of which variant was chosen.

**Comment by ghost** [comment]
Could be for a number of reasons, the most common one being simulation mode.

**Comment by fragmental** [comment]
What's the status on this?

**Comment by Cheeseness** [comment]
> What's the status on this?

When checking out your branch, I don't see the KGuNN asset variant working. @lightsoda, I don't believe this has anything to do with simulation mode - I'm seeing this in standalone builds. I feel like we should get this sorted before merging.

There's a merge conflict that's been caused by work on goals/scoring that was merged while I was away. Hopefully this won't be a big deal to resolve/integrate, but someone other than me is going to have to review/merge this.

**Comment by fragmental** [comment]
Can you confirm that it works in Master?  I can't really tell, since the bumpers look the same from the top.

**Comment by fragmental** [comment]
And I don't know why the scene shows a conflict, I think it's related to a merge that was made after my last commit.  I'm not sure the best way to resolve it.  Merge master into my branch?  Rebase?

**Comment by fragmental** [comment]
I'll check.

**Comment by fragmental** [comment]
Looks like they're the same in master as it is in the branch.  I think I actually checked that earlier and forgot.  But, as was discussed previously, kgunn's assets are placeholders currently, so maybe it's not important that variants are working at this point?  As long as it doesn't impede progress now, and won't impede progress later.

**Comment by Cheeseness** [comment]
> I think it's related to a merge that was made after my last commit. I'm not sure the best way to resolve it. Merge master into my branch? Rebase?

It's related to @VideogameScrapbook's changes that @lightsoda merged last night (and the stuff that I merged just now). I believe the changes to the table itself include adding goals and adjusting respawn height. Ideally git should be able to merge these, but I guess Unity's changed the ordering of some stuff inside the .unity file along the way and it doesn't know how to handle that.

I feel like there's risk of winding up in the same situation again, so I'd advise not addressing table changes just yet - I'd really like to avoid putting you in a situation where the variant related changes in this PR end up holding it back or vice versa. If you wanted to rework this into two PRs, that might ease things, but again, I don't want to make extra work for you

> maybe it's not important that variants are working at this point?

In the main branch, I see darker/slightly smaller bumpers when selecting the kgunn variant. In your branch, I don't see any bumper models. Placeholders or not, something's lost there. I'm uncomfortable merging that, and I'm not the right person to resolve the situation.

If any of the other @Double-Fine-Game-Club/pongball-admins want to merge without the variant stuff behaving, then that's their call.

**Pull request closed without merging**
