### PR TITLE
PongballUI

### PR DESCRIPTION
**Pull request by ehne**
Have updated the main menu with a nicer ui and splash.
got rid of old one!

### CODE REVIEW

**Comment by ghost** [comment]
~~Could you reset all the material files and not add them to the commit. Just add the files relevant to your work. Thanks in advance.~~

Nevermind, I'll check out your branch and take a look. I'm working on removing the materials in another branch so it's fine.

**Comment by ghost** [comment]
Fix that one merge conflict and I'll merge this. It seems to be minor.

**Comment by Cheeseness** [comment]
I'd prefer to not see material changes/additions in here, but as @lightsoda says, they're not a big deal.

Changes to paddle_lightsoda_prefab should not be a part of this pull request though. BaseTable.unity probably shouldn't be either?

**Comment by ehne** [comment]
Can't see the prefab you're talking about

**Comment by ghost** [comment]
@ehne Check below, 
Conflicting files
Assets/entities/paddles/prefabs/paddle_lightsoda_prefab.prefab

**Comment by ghost** [comment]
Moved to PR #30

**Pull request closed without merging**
