### PR TITLE
Third try to update kgunn's table.

### PR DESCRIPTION
**Pull request by fragmental**
Third time's the charm right?

Variants should work. EVERYTHING SHOULD WORK.

except for #47 with the weird ramp issue.  But that's not something I know how to fix, and I don't think it should cause any merge conflicts.

### CODE REVIEW

**Comment by fragmental** [comment]
Those first 4 commits are weird.  I don't know why those are there.

**Comment by Cheeseness** [comment]
Does this replace #41 or should both remain open?

**Comment by fragmental** [comment]
Replaces

**Comment by Cheeseness** [comment]
Cheers!

**Comment by Cheeseness** [comment]
This is testing well here. Going to merge!

**Comment by Cheeseness** [comment]
Many thanks ^_^

**Pull request merged**
