### PR TITLE
Remapped inputs

### PR DESCRIPTION
**Pull request by ghost**
```
Left player:
	Keyboard
		Up		- up
		Down		- down
		Right Ctrl	- pull
		Enter		- power

	Joystick 2 (360 controller)
		Left analog	- up / down
		B		- pull
		X		- power

Right player:
	Keyboard
		W		- up
		S		- down
		Space		- pull
		Left Ctrl	- power

	Joystick 1 (360 controller)
		Left analog	- up / down
		B		- pull
		X		- power
```

### CODE REVIEW

**Comment by fragmental** [comment]
What about flippers?

**Comment by Cheeseness** [comment]
Thinking about this more, I'm leaning towards having the player "hit" or "pull" or whatever we're calling it key control both flippers. That keeps the control scheme simple and concise.

Until #107 is resolved, flippers don't exist in 87% of the game (2 out of 3 variants don't have them and 4 out of 5 tables don't use them). I think fixating on them at this point to an extent that it's making it hard to make decisions about core gameplay isn't worthwhile.

**Comment by fragmental** [comment]
Does hit or pull actually do something in game, besides the animation?

#127 on flippers.  addresses buttons somewhat.

**Comment by Cheeseness** [comment]
Hit or pull is cosmetic for now. I'm leaning towards feeling that it's best as a cosmetic thing and should be done automatically to coincide with paddle collisions rather than impact the ball, but I know people are inclined to explore that and it might end up being fun.

I don't see #127 being resolved before our "end of AF" milestone, so I'm going to go ahead with a single button doing the hit animation and both flippers for now. We can adjust that down the road as part of the ongoing discussion in #115

**Comment by fragmental** [comment]
@Cheeseness that's acceptable.

My thoughts on hit/pull is that it should be more than cosmetic, unless there was one button as a sort of "taunt".  I guess triggering flippers would sort of make it coincide with an action, even if those actions are sort of unrelated.

**Comment by Cheeseness** [comment]
Yeah, that's my thought for the short term. Looking forward to seeing stuff expanded upon though!

**Comment by fragmental** [comment]
@Cheeseness I think it should be fine to leave joystick control the way it is, though.

edit: for flippers

**Comment by Cheeseness** [comment]
@fragmental Joystick controls need at least some changes. Powers aren't bound to anything right now, and so far as I can tell, neither are flippers.


OK, I'm testing this now, and I'm not sure that flipping left and right controls on the keyboard is a good idea (up and down needs to be right player, W and S needs to be left player).

I think for the sake of making it easier for me to pull all this together, I'm going to close this PR and implement changes off the current head.

**Comment by fragmental** [comment]
They should mapped to something unless someone unmapped them.  See #78

**Comment by Cheeseness** [comment]
Yeah, let's not get excited about what things should and shouldn't be. There have been lots of changes since you last worked on this stuff, and it's better to check the current versions of files in the repo than make assumptions about what the problems are.

**Pull request closed without merging**
