### PR TITLE
AssetBundles are now generated at build time for the target build pla…

### PR DESCRIPTION
**Pull request by Cheeseness**
…tform. Readded lightsoda playfield detail mat.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Looks good

**Comment by fragmental** [comment]
So, does this mean you no longer have to go to AssetBundles>Build Asset Bundles before building the game?

**Comment by Cheeseness** [comment]
No, this PR was closed without being merged (Unity was crashing when trying to build asset bundles automatically as part of the post-build process).

**Comment by ghost** [comment]
Yeah I prematurely approved it, but after some testing we found that it crashed on build.

**Pull request closed without merging**
